# Generates forwarding headers for #include directives whose spelling differs from
# the actual file name only in letter case (e.g. "stdafx.h" for StdAfx.h). Windows
# file systems resolve those; Linux file systems do not. Generating the aliases keeps
# the upstream sources unchanged.
#
# The aliases are refreshed on every CMake configure run. A new mismatched include
# added later shows up as "No such file or directory" until CMake is re-run.
#
# meos_generate_case_aliases(<output dir>
#                            SOURCES <files that contain #include directives>
#                            SEARCH_DIRS <directories that contain project headers>)

function(meos_generate_case_aliases out_dir)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "SOURCES;SEARCH_DIRS")

  file(MAKE_DIRECTORY "${out_dir}")

  # Index all project headers by their lower-case path relative to each search dir.
  foreach(dir IN LISTS ARG_SEARCH_DIRS)
    file(GLOB_RECURSE headers RELATIVE "${dir}" "${dir}/*.h" "${dir}/*.hpp")
    foreach(header IN LISTS headers)
      string(TOLOWER "${header}" key)
      if(NOT DEFINED _meos_header_${key})
        set(_meos_header_${key} "${dir}/${header}")
      endif()
    endforeach()
  endforeach()

  set(created "")
  foreach(source IN LISTS ARG_SOURCES)
    get_filename_component(source_dir "${source}" DIRECTORY)
    file(STRINGS "${source}" lines REGEX "^[ \t]*#[ \t]*include[ \t]*[\"<][^\">]+[\">]")
    foreach(line IN LISTS lines)
      string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*[\"<]([^\">]+)[\">].*$" "\\1" include "${line}")
      string(REPLACE "\\" "/" include "${include}")
      if(include IN_LIST created)
        continue()
      endif()

      set(exact_match FALSE)
      foreach(dir IN ITEMS "${source_dir}" LISTS ARG_SEARCH_DIRS)
        if(EXISTS "${dir}/${include}")
          set(exact_match TRUE)
          break()
        endif()
      endforeach()
      if(exact_match)
        continue()
      endif()

      string(TOLOWER "${include}" key)
      if(DEFINED _meos_header_${key})
        set(target "${_meos_header_${key}}")
        file(CONFIGURE OUTPUT "${out_dir}/${include}"
             CONTENT "// Generated by code/cmake/CaseAliases.cmake - do not edit.\n#include \"${target}\"\n")
        list(APPEND created "${include}")
      endif()
    endforeach()
  endforeach()

  list(LENGTH created count)
  message(STATUS "MeOS: ${count} case alias header(s) generated in ${out_dir}")
endfunction()
