# Embeds the resources of Windows resource scripts (.rc) as Qt resources, so that
# FindResource and LoadResource work on Linux (platform/qt/win32_resources.cpp).
#
# Only single-line statements of the form
#     <name> <type> [load/memory attributes] "<file>"
# are read (images, language tables, sounds, HTML). Menus, dialogs, accelerators and
# version information span several lines and are skipped. Symbols are resolved with
# the #define lines of the given headers and of the scripts themselves, as the
# preprocessor of the resource compiler does. New resources of an upstream drop
# therefore need no manual work.
#
# Every resource becomes the Qt resource ":/meos/resources/<type>/<name>":
#   - <type> is the number of a predefined type (BITMAP = 2, ICON = 14, HTML = 23,
#     RCDATA = 10, ...), a numeric type as written, or the type name in upper case
#     (PNG, WAVE);
#   - <name> is the resolved number or the name in upper case.
# The file content is embedded unchanged; win32_resources.cpp removes the
# BITMAPFILEHEADER of bitmaps as the resource compiler does.
#
# meos_generate_win32_resources(<output .qrc>
#                               RC_FILES <resource scripts>
#                               HEADERS <headers with #define lines>)

function(meos_generate_win32_resources qrc_file)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "RC_FILES;HEADERS")

  set(symbol_regex "^[ \t]*#[ \t]*define[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]+(0[xX][0-9a-fA-F]+|[0-9]+)[ \t]*$")
  foreach(file IN LISTS ARG_HEADERS ARG_RC_FILES)
    file(STRINGS "${file}" lines REGEX "^[ \t]*#[ \t]*define[ \t]")
    foreach(line IN LISTS lines)
      string(REPLACE "\r" "" line "${line}")
      if(line MATCHES "${symbol_regex}")
        math(EXPR value "${CMAKE_MATCH_2}")
        set(_meos_symbol_${CMAKE_MATCH_1} "${value}")
      endif()
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
  endforeach()

  # Predefined resource types (RT_*) of the statements that name a file.
  set(_meos_type_CURSOR 12)
  set(_meos_type_BITMAP 2)
  set(_meos_type_ICON 14)
  set(_meos_type_FONT 8)
  set(_meos_type_RCDATA 10)
  set(_meos_type_MESSAGETABLE 11)
  set(_meos_type_HTML 23)
  set(_meos_type_MANIFEST 24)

  set(attribute "[ \t]+(PRELOAD|LOADONCALL|FIXED|MOVEABLE|DISCARDABLE|PURE|IMPURE)")
  set(resource_regex "^[ \t]*([A-Za-z0-9_]+)[ \t]+([A-Za-z0-9_]+)(${attribute})*[ \t]+\"([^\"]+)\"[ \t]*$")

  set(entries "")
  set(keys "")
  foreach(rc_file IN LISTS ARG_RC_FILES)
    get_filename_component(rc_dir "${rc_file}" DIRECTORY)
    file(STRINGS "${rc_file}" lines)
    foreach(line IN LISTS lines)
      string(REPLACE "\r" "" line "${line}")
      if(NOT line MATCHES "${resource_regex}")
        continue()
      endif()
      set(name "${CMAKE_MATCH_1}")
      set(type "${CMAKE_MATCH_2}")
      set(path "${CMAKE_MATCH_5}")

      foreach(token name type)
        if(DEFINED _meos_symbol_${${token}})
          set(${token} "${_meos_symbol_${${token}}}")
        endif()
      endforeach()
      string(TOUPPER "${type}" type_upper)
      if(DEFINED _meos_type_${type_upper})
        set(type "${_meos_type_${type_upper}}")
      elseif(NOT type MATCHES "^[0-9]+$")
        set(type "${type_upper}")
      endif()
      if(NOT name MATCHES "^[0-9]+$")
        string(TOUPPER "${name}" name)
      endif()

      # The resource compiler finds files regardless of letter case (meos.ICO).
      string(REPLACE "\\" "/" path "${path}")
      get_filename_component(path "${path}" ABSOLUTE BASE_DIR "${rc_dir}")
      if(NOT EXISTS "${path}")
        get_filename_component(file_dir "${path}" DIRECTORY)
        get_filename_component(file_name "${path}" NAME)
        string(TOLOWER "${file_name}" wanted)
        file(GLOB candidates RELATIVE "${file_dir}" "${file_dir}/*")
        set(found "")
        foreach(candidate IN LISTS candidates)
          string(TOLOWER "${candidate}" lower)
          if(lower STREQUAL wanted)
            set(found "${file_dir}/${candidate}")
          endif()
        endforeach()
        if(NOT found)
          message(FATAL_ERROR "${rc_file}: resource file not found: ${path}")
        endif()
        set(path "${found}")
      endif()

      set(key "${type}/${name}")
      if(key IN_LIST keys)
        message(FATAL_ERROR "${rc_file}: duplicate resource ${key}")
      endif()
      list(APPEND keys "${key}")
      string(REPLACE "&" "&amp;" xml_path "${path}")
      string(APPEND entries "    <file alias=\"${key}\">${xml_path}</file>\n")
    endforeach()
  endforeach()

  set(content "<!DOCTYPE RCC>\n<!-- Generated by cmake/Win32Resources.cmake. -->\n<RCC version=\"1.0\">\n")
  string(APPEND content "  <qresource prefix=\"/meos/resources\">\n${entries}  </qresource>\n</RCC>\n")
  # Rewritten only on change, so that the resources are not rebuilt on every run.
  file(WRITE "${qrc_file}.tmp" "${content}")
  configure_file("${qrc_file}.tmp" "${qrc_file}" COPYONLY)
  file(REMOVE "${qrc_file}.tmp")
endfunction()
